// OperationalWorkspace — reusable, production-style mock pages for the remaining DAOS workspaces.
// All values are illustrative UI data; no backend or connectivity is implied.
import { h, React } from '../lib/dom.js';
import { DataGrid } from '../components/DataGrid.js';

const CONFIG = {
  deals: { title: 'Opportunity & Deal Management', icon: '🤝', subtitle: 'Pipeline, diligence and deal structuring', tabs: [['overview','Pipeline'],['diligence','Due Diligence'],['approvals','Approvals']], rows: [
    { id:'OPP-1042', name:'Northstar Infrastructure', stage:'Diligence', owner:'M. Chen', value:'$184M', updated:'Today' }, { id:'OPP-1038', name:'Atlas Credit Fund', stage:'Structuring', owner:'J. Sullivan', value:'$92M', updated:'Yesterday' }, { id:'OPP-1031', name:'Orion Renewables', stage:'IC Review', owner:'R. Brown', value:'$61M', updated:'Jul 28' }, { id:'OPP-1027', name:'Harbor Digital Income', stage:'Term Sheet', owner:'A. Kim', value:'$38M', updated:'Jul 27' } ] },
  investments: { title:'Investment Management', icon:'📊', subtitle:'Research, mandates and portfolio decisions', tabs:[['overview','Portfolio Overview'],['research','Research'],['orders','Investment Orders']], rows:[
    { id:'PORT-001', name:'Global Multi-Asset', status:'On target', owner:'M. Chen', value:'$2.41B', updated:'Today' }, { id:'PORT-004', name:'Digital Opportunities', status:'Review', owner:'A. Kim', value:'$486M', updated:'Today' }, { id:'PORT-007', name:'Liquidity Reserve', status:'On target', owner:'S. Lee', value:'$1.12B', updated:'Yesterday' }, { id:'PORT-009', name:'EM Credit', status:'Watch', owner:'J. Sullivan', value:'$734M', updated:'Jul 28' } ] },
  products: { title:'Product & Fund Operations', icon:'📦', subtitle:'Funds, products, NAV and lifecycle controls', tabs:[['overview','Product Overview'],['nav','NAV Operations'],['lifecycle','Lifecycle']], rows:[
    { id:'FUND-001', name:'BR Global Fund I', status:'NAV published', jurisdiction:'LU', value:'$2.41B', updated:'14:32 UTC' }, { id:'FUND-002', name:'BR Digital Assets Feeder', status:'Awaiting NAV', jurisdiction:'BVI', value:'$186M', updated:'13:58 UTC' }, { id:'FUND-003', name:'BR Prime Liquidity Token', status:'Active', jurisdiction:'US', value:'$892M', updated:'12:44 UTC' }, { id:'FUND-004', name:'BR Sustainable Credit', status:'Review', jurisdiction:'IE', value:'$318M', updated:'Yesterday' } ] },
  'digital-rep': { title:'Digital Representation', icon:'⛓️', subtitle:'Token, digital money and representation controls', tabs:[['overview','Representation Overview'],['issuance','Issuance'],['reconciliation','Reconciliation']], rows:[
    { id:'REP-001', name:'BR Prime Liquidity Token', network:'Ethereum', status:'Active', supply:'892.4M', updated:'2 min ago' }, { id:'REP-002', name:'EU Green Bond 2026', network:'Polygon', status:'Pending', supply:'120.0M', updated:'1 hour ago' }, { id:'REP-003', name:'USD Settlement Cash', network:'Internal ledger', status:'Active', supply:'1.4B', updated:'5 min ago' }, { id:'REP-004', name:'Fund I Share Class D', network:'Private network', status:'Reconcile', supply:'64.2M', updated:'Yesterday' } ] },
  investors: { title:'Investor & Ownership Operations', icon:'💰', subtitle:'Transfer agency, ownership and investor servicing', tabs:[['overview','Investor Overview'],['transfers','Transfers'],['communications','Communications']], rows:[
    { id:'INV-20384', name:'Asteria Pension Trust', type:'Institutional', status:'Active', holdings:'$84.2M', updated:'Today' }, { id:'INV-20371', name:'Meridian Family Office', type:'Family Office', status:'KYC refresh', holdings:'$12.8M', updated:'Yesterday' }, { id:'INV-20355', name:'Northbank Private Bank', type:'Distributor', status:'Active', holdings:'$216M', updated:'Jul 28' }, { id:'INV-20342', name:'Cedar Endowment', type:'Institutional', status:'Pending', holdings:'$31.4M', updated:'Jul 27' } ] },
  transactions: { title:'Transaction Operations', icon:'💹', subtitle:'Trading, portfolios and transaction lifecycle', tabs:[['overview','Transaction Overview'],['orders','Orders'],['exceptions','Exceptions']], rows:[
    { id:'TRD-78421', name:'AAPL / Buy', type:'Equity', status:'Settled', amount:'$1.95M', updated:'14:26 UTC' }, { id:'TRD-78418', name:'US10Y / Sell', type:'Fixed Income', status:'Matched', amount:'$8.20M', updated:'14:18 UTC' }, { id:'TRD-78402', name:'BTC / Buy', type:'Digital Asset', status:'Exception', amount:'$4.80M', updated:'13:52 UTC' }, { id:'TRD-78396', name:'EUR/USD / Buy', type:'FX', status:'Affirmed', amount:'€2.10M', updated:'13:41 UTC' } ] },
  treasury: { title:'Treasury & Liquidity', icon:'🏦', subtitle:'Cash, funding and foreign exchange management', tabs:[['overview','Liquidity Overview'],['cash','Cash Positions'],['fx','FX Exposure']], rows:[
    { id:'CASH-001', name:'USD Operating Cash', bank:'Northbank', status:'Available', balance:'$842.6M', updated:'14:30 UTC' }, { id:'CASH-002', name:'EUR Settlement Cash', bank:'Euroclear', status:'Available', balance:'€318.4M', updated:'14:28 UTC' }, { id:'CASH-003', name:'GBP Custody Cash', bank:'Meridian', status:'Reconcile', balance:'£94.2M', updated:'13:55 UTC' }, { id:'CASH-004', name:'JPY Reserve', bank:'Tokyo Trust', status:'Available', balance:'¥18.6B', updated:'Yesterday' } ] },
  custody: { title:'Custody Operations', icon:'🔐', subtitle:'Safekeeping, servicing and account controls', tabs:[['overview','Custody Overview'],['accounts','Accounts'],['servicing','Asset Servicing']], rows:[
    { id:'CUST-0456', name:'Northbank Custody', jurisdiction:'US', status:'Reconciled', assets:'$18.4B', updated:'14:20 UTC' }, { id:'CUST-0457', name:'Euroclear Bank', jurisdiction:'BE', status:'2 breaks', assets:'€7.2B', updated:'14:12 UTC' }, { id:'CUST-0458', name:'Copper Technologies', jurisdiction:'GB', status:'Reconciled', assets:'$2.8B', updated:'13:44 UTC' }, { id:'CUST-0459', name:'Tokyo Trust', jurisdiction:'JP', status:'Review', assets:'¥420B', updated:'Yesterday' } ] },
  settlement: { title:'Settlement Network', icon:'🤖', subtitle:'Post-trade, matching and payment coordination', tabs:[['overview','Settlement Control Tower'],['instructions','Instructions'],['fails','Settlement Fails']], rows:[
    { id:'STL-000456', name:'DTCC — Equity', network:'DTCC', status:'Failed', amount:'$2.4M', updated:'4 min ago' }, { id:'STL-000455', name:'Euroclear — Bond', network:'Euroclear', status:'Settled', amount:'€8.2M', updated:'12 min ago' }, { id:'STL-000454', name:'Internal — Token', network:'DAOS Ledger', status:'Settled', amount:'$5.6M', updated:'18 min ago' }, { id:'STL-000453', name:'SWIFT — FX', network:'SWIFT', status:'Pending', amount:'£1.2M', updated:'26 min ago' } ] },
  'data-intel': { title:'Data & Intelligence', icon:'🧠', subtitle:'Data quality, lineage and decision intelligence', tabs:[['overview','Data Health'],['quality','Data Quality'],['lineage','Lineage & Controls']], rows:[
    { id:'DATA-001', name:'Market Data — Equities', domain:'Market Data', status:'Healthy', records:'4.2M', updated:'2 min ago' }, { id:'DATA-002', name:'Participant Master', domain:'Reference', status:'Healthy', records:'18,402', updated:'15 min ago' }, { id:'DATA-003', name:'Positions — Custody', domain:'Positions', status:'Review', records:'2.8M', updated:'1 hour ago' }, { id:'DATA-004', name:'ESG Classifications', domain:'Reference', status:'Degraded', records:'842K', updated:'Yesterday' } ] },
  admin: { title:'Enterprise Administration', icon:'⚙️', subtitle:'Platform configuration, access and controls', tabs:[['overview','Administration Overview'],['users','Users & Roles'],['integrations','Integrations']], rows:[
    { id:'CFG-001', name:'Identity Provider', type:'Security', status:'Connected', owner:'Platform Ops', updated:'Today' }, { id:'CFG-002', name:'DTCC Connection', type:'Integration', status:'Connected', owner:'Settlement Ops', updated:'Yesterday' }, { id:'CFG-003', name:'Approval Policies', type:'Governance', status:'3 pending', owner:'Risk Team', updated:'Jul 28' }, { id:'CFG-004', name:'Jurisdiction Rules', type:'Configuration', status:'Review', owner:'Legal Ops', updated:'Jul 25' } ] }
};

function statusCell(value) { const good = ['Active','Healthy','Connected','Settled','Matched','Available','On target','Reconciled','NAV published','Affirmed']; const bad = ['Failed','Degraded','Exception','2 breaks','Review','Reconcile','3 pending','Watch']; const cls = good.includes(value) ? 'text-status-success bg-status-success/10 border-status-success/30' : bad.includes(value) ? 'text-status-warning bg-status-warning/10 border-status-warning/30' : 'text-daos-300 bg-daos-500/10 border-daos-500/30'; return h('span',{className:`inline-block px-2 py-0.5 rounded-full border text-2xs ${cls}`},value); }

function Header({config, page}) { return h('div',{className:'flex items-center justify-between px-4 py-3 border-b border-surface-border bg-surface-raised/50'},h('div',{},h('div',{className:'flex items-center gap-2'},h('span',{className:'text-lg'},config.icon),h('h2',{className:'text-sm font-semibold text-slate-200'},config.title)),h('p',{className:'text-xs text-slate-500 mt-1'},config.subtitle)),h('div',{className:'flex items-center gap-2'},h('span',{className:'text-2xs text-slate-500'},'Illustrative workspace data'),h('button',{className:'px-2 py-1 text-xs text-slate-300 border border-surface-border rounded hover:bg-surface-overlay focus-ring'},'Export'))); }

function Summary({config}) { return h('div',{className:'grid grid-cols-2 md:grid-cols-4 gap-3 p-4 border-b border-surface-border'},['Records in view','Active workflows','Needs attention','Last refresh'].map((label,i)=>h('div',{key:label,className:'rounded-lg border border-surface-border bg-surface-raised p-3'},h('div',{className:'text-2xs uppercase tracking-wider text-slate-500'},label),h('div',{className:'text-xl font-semibold text-slate-100 mt-1'},[config.rows.length*4,'18','3','14:32'][i]),h('div',{className:`text-2xs mt-1 ${i===2?'text-status-warning':'text-status-success'}`},i===2?'Requires review':'Within operating target')))); }

export function OperationalWorkspace({workspaceId, page='overview'}) { const config=CONFIG[workspaceId] || CONFIG.deals; const [activeTab,setActiveTab]=React.useState(page); React.useEffect(()=>setActiveTab(page),[page]); const columns=Object.keys(config.rows[0]).map(key=>({key,label:key==='id'?'Reference':key.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase()),sortable:true,render:key==='status'?(v)=>statusCell(v):undefined})); return h('div',{className:'flex flex-col h-full'},h(Header,{config,page:activeTab}),h('div',{className:'flex gap-1 px-4 pt-3 border-b border-surface-border'},...config.tabs.map(([id,label])=>h('button',{key:id,onClick:()=>setActiveTab(id),className:`px-3 py-2 text-xs rounded-t focus-ring ${activeTab===id?'text-daos-300 border-b-2 border-daos-500 bg-daos-900/20':'text-slate-500 hover:text-slate-300'}`},label))),h(Summary,{config}),h('div',{className:'flex-1 overflow-hidden'},h(DataGrid,{data:config.rows,columns,idKey:'id'}))); }

export const OPERATIONAL_WORKSPACES = Object.keys(CONFIG);
